/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.jzinv.vat1050;

import nc.itf.jzinv.pub.IBillCode;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;

/**
 * <b> 项目税金计算 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2016-04-10 14:23:45
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class VatProjanalyVO extends SuperVO implements IBillCode {
	private String pk_corp;
	private UFDouble nintooutmny;
	private UFBoolean bisbegin;
	private String vdef4;
	private String vreserve5;
	private String vdef18;
	private String pk_uppertaxorg;
	private Integer dr;
	private String pk_project;
	private String voperatorid;
	private String vdef16;
	private String vdef17;
	private String vapprovenote;
	private String vdef27;
	private String vdef12;
	private UFDouble ntaxablemny;
	private String vdef24;
	private UFDateTime ts;
	private String pk_receunit;
	private String vreserve9;
	private String vdef25;
	private UFDouble ntaxablesalemny;
	private String pk_basetype;
	private String vdef19;
	private String pk_deptdoc;
	private String vdef3;
	private String vdef13;
	private String vreserve6;
	private String pk_projanaly;
	private String vreserve10;
	private String vdef28;
	private UFDouble ntaxableinmny;
	private String vreserve3;
	private String vdef23;
	private String vreserve4;
	private String vdef29;
	private String vdef10;
	private UFDouble nlresttaxmny;
	private String vdef5;
	private String pk_psndoc;
	private String vreserve8;
	private String vdef11;
	private UFDouble nresttaxmny;
	private UFDate dmakedate;
	private String vdef7;
	private UFDouble nsaletaxmny;
	private String vdef20;
	private String pk_billtype;
	private Integer vbillstatus;
	private String vreserve2;
	private String vdef2;
	private String vmemo;
	private UFDouble nintaxmny;
	private String pk_busitype;
	private String pk_projectbase;
	private String vdef1;
	private String vperiod;
	private String vbillno;
	private UFDate dbilldate;
	private String vdef26;
	private String vdef14;
	private String vdef21;
	private String pk_taxorg;
	private UFDouble ntaxes;
	private String vreserve1;
	private String vreserve7;
	private String vdef9;
	private String vdef8;
	private UFDate dapprovedate;
	private String vapproveid;
	private String vdef30;
	private String vdef6;
	private String vdef15;
	private String pk_receunit_base;
	private String vdef22;
	private UFDouble nthhadauthtaxmny;
	// 新增字段
	private UFDouble npaidtaxmny;// 应上缴税额
	/**
	 * 是否传会计凭证
	 */
	private UFBoolean bisupload;

	public static final String BISUPLOAD = "bisupload";
	/**
	 * 销售额
	 */
	private UFDouble nsalemny;
	/**
	 * 本期费用扣除金额
	 */
	private UFDouble nthcutmny;
	/**
	 * 本期费用留抵扣除金额
	 */
	private UFDouble nthrestcutmny;
	/**
	 * 上期费用留抵扣除金额
	 */
	private UFDouble nlrestcutmny;
	public static final String PK_CORP = "pk_corp";
	/**
	 * 本期费用扣除金额
	 */
	public static final String NTHCUTMNY = "nthcutmny";
	/**
	 * 本期费用留抵扣除金额
	 */
	public static final String NTHRESTCUTMNY = "nthrestcutmny";
	/**
	 * 上期费用留抵扣除金额
	 */
	public static final String NLRESTCUTMNY = "nlrestcutmny";
	/**
	 * 销售额
	 */
	public static final String NSALEMNY = "nsalemny";
	/**
	 * 进项转出
	 */
	public static final String NINTOOUTMNY = "nintooutmny";
	public static final String BISBEGIN = "bisbegin";
	public static final String VDEF4 = "vdef4";
	public static final String VRESERVE5 = "vreserve5";
	public static final String VDEF18 = "vdef18";
	public static final String PK_UPPERTAXORG = "pk_uppertaxorg";
	public static final String PK_PROJECT = "pk_project";
	public static final String VOPERATORID = "voperatorid";
	public static final String VDEF16 = "vdef16";
	public static final String VDEF17 = "vdef17";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String VDEF27 = "vdef27";
	public static final String VDEF12 = "vdef12";
	/**
	 * 应缴税额
	 */
	public static final String NTAXABLEMNY = "ntaxablemny";
	public static final String VDEF24 = "vdef24";
	public static final String PK_RECEUNIT = "pk_receunit";
	public static final String VRESERVE9 = "vreserve9";
	public static final String VDEF25 = "vdef25";
	// 新增字段
	public static final String NPAIDTAXMNY = "npaidtaxmny";// 应上缴税额
	/**
	 * 应税销售额
	 */
	public static final String NTAXABLESALEMNY = "ntaxablesalemny";
	public static final String PK_BASETYPE = "pk_basetype";
	public static final String VDEF19 = "vdef19";
	public static final String PK_DEPTDOC = "pk_deptdoc";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF13 = "vdef13";
	public static final String VRESERVE6 = "vreserve6";
	public static final String PK_PROJANALY = "pk_projanaly";
	public static final String VRESERVE10 = "vreserve10";
	public static final String VDEF28 = "vdef28";
	/**
	 * 应税进项额
	 */
	public static final String NTAXABLEINMNY = "ntaxableinmny";
	public static final String VRESERVE3 = "vreserve3";
	public static final String VDEF23 = "vdef23";
	public static final String VRESERVE4 = "vreserve4";
	public static final String VDEF29 = "vdef29";
	public static final String VDEF10 = "vdef10";
	/**
	 * 上期留抵税额
	 */
	public static final String NLRESTTAXMNY = "nlresttaxmny";
	public static final String VDEF5 = "vdef5";
	public static final String PK_PSNDOC = "pk_psndoc";
	public static final String VRESERVE8 = "vreserve8";
	public static final String VDEF11 = "vdef11";
	/**
	 * 留抵税额
	 */
	public static final String NRESTTAXMNY = "nresttaxmny";
	public static final String DMAKEDATE = "dmakedate";
	public static final String VDEF7 = "vdef7";
	/**
	 * 销项税额
	 */
	public static final String NSALETAXMNY = "nsaletaxmny";
	public static final String VDEF20 = "vdef20";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String VRESERVE2 = "vreserve2";
	public static final String VDEF2 = "vdef2";
	public static final String VMEMO = "vmemo";
	/**
	 * 进项税额
	 */
	public static final String NINTAXMNY = "nintaxmny";
	public static final String PK_BUSITYPE = "pk_busitype";
	public static final String PK_PROJECTBASE = "pk_projectbase";
	public static final String VDEF1 = "vdef1";
	public static final String VPERIOD = "vperiod";
	public static final String VBILLNO = "vbillno";
	public static final String DBILLDATE = "dbilldate";
	public static final String VDEF26 = "vdef26";
	public static final String VDEF14 = "vdef14";
	public static final String VDEF21 = "vdef21";
	/**
	 * 本期已认证税额
	 */
	public static final String NTHHADAUTHTAXMNY = "nthhadauthtaxmny";
	public static final String PK_TAXORG = "pk_taxorg";
	/**
	 * 应缴税负
	 */
	public static final String NTAXES = "ntaxes";
	public static final String VRESERVE1 = "vreserve1";
	public static final String VRESERVE7 = "vreserve7";
	public static final String VDEF9 = "vdef9";
	public static final String VDEF8 = "vdef8";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String VAPPROVEID = "vapproveid";
	public static final String VDEF30 = "vdef30";
	public static final String VDEF6 = "vdef6";
	public static final String VDEF15 = "vdef15";
	public static final String PK_RECEUNIT_BASE = "pk_receunit_base";
	public static final String VDEF22 = "vdef22";

	private String vsourcebilltype;
	private String vsourcebillid;
	private String vsourcebillrowid;
	private String vlastbilltype;
	private String vlastbillid;
	private String vlastbillrowid;

	public static final String VSOURCEBILLTYPE = "vsourcebilltype";
	public static final String VSOURCEBILLID = "vsourcebillid";
	public static final String VSOURCEBILLROWID = "vsourcebillrowid";
	public static final String VLASTBILLTYPE = "vlastbilltype";
	public static final String VLASTBILLID = "vlastbillid";
	public static final String VLASTBILLROWID = "vlastbillrowid";
	
	
	public UFDouble getNpaidtaxmny() {
		return npaidtaxmny;
	}

	public void setNpaidtaxmny(UFDouble npaidtaxmny) {
		this.npaidtaxmny = npaidtaxmny;
	}

	/**
	 * 预缴税额		
	 */
	private UFDouble nprepaytaxmny;
	/**
	 * 预缴税额		
	 */
	public static final String NPREPAYTAXMNY = "nprepaytaxmny";
	/**
	 * 项目计税方式
	 */
	private Integer itaxtype;
	/**
	 * 项目计税方式
	 */
	public static final String ITAXTYPE = "itaxtype";
	/**
	 * 项目销售额
	 */
	private UFDouble nprojsalemny;
	/**
	 * 项目销售额
	 */
	public static final String NPROJSALEMNY = "nprojsalemny";

	/**
	 * 本期认证不可抵扣
	 */
	private UFDouble nthauthnocutmny;
	/**
	 * 本期认证不可抵扣
	 */
	public static final String NTHAUTHNOCUTMNY = "nthauthnocutmny";
	/**
	 * 前期认证本期抵扣
	 */
	private UFDouble nlauththcutmny;
	/**
	 * 前期认证本期抵扣
	 */
	public static final String NLAUTHTHCUTMNY = "nlauththcutmny";
	/*
	 * 项目税金计算表名称
	 */
	public static final String TABNAME = "jzinv_vat_projanaly";

	public UFBoolean getBisupload() {
		return bisupload;
	}

	public void setBisupload(UFBoolean bisupload) {
		this.bisupload = bisupload;
	}

	public UFDouble getNthauthnocutmny() {
		return nthauthnocutmny;
	}

	public void setNthauthnocutmny(UFDouble nthauthnocutmny) {
		this.nthauthnocutmny = nthauthnocutmny;
	}

	public UFDouble getNlauththcutmny() {
		return nlauththcutmny;
	}

	public void setNlauththcutmny(UFDouble nlauththcutmny) {
		this.nlauththcutmny = nlauththcutmny;
	}

	public String getVsourcebilltype() {
		return vsourcebilltype;
	}

	public void setVsourcebilltype(String vsourcebilltype) {
		this.vsourcebilltype = vsourcebilltype;
	}

	public String getVsourcebillid() {
		return vsourcebillid;
	}

	public void setVsourcebillid(String vsourcebillid) {
		this.vsourcebillid = vsourcebillid;
	}

	public String getVsourcebillrowid() {
		return vsourcebillrowid;
	}

	public void setVsourcebillrowid(String vsourcebillrowid) {
		this.vsourcebillrowid = vsourcebillrowid;
	}

	public String getVlastbilltype() {
		return vlastbilltype;
	}

	public void setVlastbilltype(String vlastbilltype) {
		this.vlastbilltype = vlastbilltype;
	}

	public String getVlastbillid() {
		return vlastbillid;
	}

	public void setVlastbillid(String vlastbillid) {
		this.vlastbillid = vlastbillid;
	}

	public String getVlastbillrowid() {
		return vlastbillrowid;
	}

	public void setVlastbillrowid(String vlastbillrowid) {
		this.vlastbillrowid = vlastbillrowid;
	}

	public UFDouble getNthrestcutmny() {
		return nthrestcutmny;
	}

	public void setNthrestcutmny(UFDouble nthrestcutmny) {
		this.nthrestcutmny = nthrestcutmny;
	}

	public UFDouble getNlrestcutmny() {
		return nlrestcutmny;
	}

	public void setNlrestcutmny(UFDouble nlrestcutmny) {
		this.nlrestcutmny = nlrestcutmny;
	}

	public UFDouble getNprojsalemny() {
		return nprojsalemny;
	}

	public void setNprojsalemny(UFDouble nprojsalemny) {
		this.nprojsalemny = nprojsalemny;
	}

	public UFDouble getNprepaytaxmny() {
		return nprepaytaxmny;
	}

	public void setNprepaytaxmny(UFDouble nprepaytaxmny) {
		this.nprepaytaxmny = nprepaytaxmny;
	}

	public Integer getItaxtype() {
		return itaxtype;
	}

	public void setItaxtype(Integer itaxtype) {
		this.itaxtype = itaxtype;
	}

	/****************测算用 begin******************/
	/**
	 * 优先反算(测算用)
	 */
	public static final String IPRIORINVERSECALCU = "ipriorinversecalcu";
	/**
	 *综合税率
	 */
	private UFDouble navgtax;

	public static final String NCALSALETAXMNY = "ncalsaletaxmny";
	/**
	 * 测算进项认证税额
	 */
	public static final String NCALINCATAXMNY = "ncalincataxmny";
	/**
	 * 测算税负
	 */
	public static final String NCALTAXES = "ncaltaxes";
	/**
	 * 测算应缴税额
	 */
	public static final String NCALTAXABLEMNY = "ncaltaxablemny";
	/**
	 * 调整应税销售额
	 */
	public static final String NADJTAXABLESALEMNY = "nadjtaxablesalemny";
	/**
	 * 调整销项税额
	 */
	public static final String NADJSALETAXMNY = "nadjsaletaxmny";
	/**
	 * 综合税率
	 */
	public static final String NAVGTAX = "navgtax";
	/**
	 * 可认证进项税额
	 */
	public static final String NSHINCATAXMNY = "nshincataxmny";
	/**
	 * 分包进项应税额
	 */
	public static final String NSUBTAXABLEINMNY = "nsubtaxableinmny";

	/****************测算用 end******************/
	public UFDouble getNavgtax() {
		return navgtax;
	}

	public void setNavgtax(UFDouble navgtax) {
		this.navgtax = navgtax;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_corp String
	 */
	public void setPk_corp(String newPk_corp) {
		this.pk_corp = newPk_corp;
	}

	/**
	 * 属性nintooutmny的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDouble
	 */
	public UFDouble getNintooutmny() {
		return nintooutmny;
	}

	/**
	 * 属性nintooutmny的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newNintooutmny UFDouble
	 */
	public void setNintooutmny(UFDouble newNintooutmny) {
		this.nintooutmny = newNintooutmny;
	}

	/**
	 * 属性bisbegin的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFBoolean
	 */
	public UFBoolean getBisbegin() {
		return bisbegin;
	}

	/**
	 * 属性bisbegin的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newBisbegin UFBoolean
	 */
	public void setBisbegin(UFBoolean newBisbegin) {
		this.bisbegin = newBisbegin;
	}

	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef4() {
		return vdef4;
	}

	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef4 String
	 */
	public void setVdef4(String newVdef4) {
		this.vdef4 = newVdef4;
	}

	/**
	 * 属性vreserve5的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVreserve5() {
		return vreserve5;
	}

	/**
	 * 属性vreserve5的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVreserve5 String
	 */
	public void setVreserve5(String newVreserve5) {
		this.vreserve5 = newVreserve5;
	}

	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef18() {
		return vdef18;
	}

	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef18 String
	 */
	public void setVdef18(String newVdef18) {
		this.vdef18 = newVdef18;
	}

	/**
	 * 属性pk_uppertaxorg的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_uppertaxorg() {
		return pk_uppertaxorg;
	}

	/**
	 * 属性pk_uppertaxorg的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_uppertaxorg String
	 */
	public void setPk_uppertaxorg(String newPk_uppertaxorg) {
		this.pk_uppertaxorg = newPk_uppertaxorg;
	}

	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newDr Integer
	 */
	public void setDr(Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性pk_project的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_project() {
		return pk_project;
	}

	/**
	 * 属性pk_project的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_project String
	 */
	public void setPk_project(String newPk_project) {
		this.pk_project = newPk_project;
	}

	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVoperatorid String
	 */
	public void setVoperatorid(String newVoperatorid) {
		this.voperatorid = newVoperatorid;
	}

	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef16() {
		return vdef16;
	}

	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef16 String
	 */
	public void setVdef16(String newVdef16) {
		this.vdef16 = newVdef16;
	}

	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef17() {
		return vdef17;
	}

	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef17 String
	 */
	public void setVdef17(String newVdef17) {
		this.vdef17 = newVdef17;
	}

	/**
	 * 属性vapprovenote的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVapprovenote String
	 */
	public void setVapprovenote(String newVapprovenote) {
		this.vapprovenote = newVapprovenote;
	}

	/**
	 * 属性vdef27的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef27() {
		return vdef27;
	}

	/**
	 * 属性vdef27的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef27 String
	 */
	public void setVdef27(String newVdef27) {
		this.vdef27 = newVdef27;
	}

	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef12() {
		return vdef12;
	}

	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef12 String
	 */
	public void setVdef12(String newVdef12) {
		this.vdef12 = newVdef12;
	}

	/**
	 * 属性ntaxablemny的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDouble
	 */
	public UFDouble getNtaxablemny() {
		return ntaxablemny;
	}

	/**
	 * 属性ntaxablemny的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newNtaxablemny UFDouble
	 */
	public void setNtaxablemny(UFDouble newNtaxablemny) {
		this.ntaxablemny = newNtaxablemny;
	}

	/**
	 * 属性vdef24的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef24() {
		return vdef24;
	}

	/**
	 * 属性vdef24的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef24 String
	 */
	public void setVdef24(String newVdef24) {
		this.vdef24 = newVdef24;
	}

	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDateTime
	 */
	public UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newTs UFDateTime
	 */
	public void setTs(UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * 属性pk_receunit的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_receunit() {
		return pk_receunit;
	}

	/**
	 * 属性pk_receunit的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_receunit String
	 */
	public void setPk_receunit(String newPk_receunit) {
		this.pk_receunit = newPk_receunit;
	}

	/**
	 * 属性vreserve9的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVreserve9() {
		return vreserve9;
	}

	/**
	 * 属性vreserve9的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVreserve9 String
	 */
	public void setVreserve9(String newVreserve9) {
		this.vreserve9 = newVreserve9;
	}

	/**
	 * 属性vdef25的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef25() {
		return vdef25;
	}

	/**
	 * 属性vdef25的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef25 String
	 */
	public void setVdef25(String newVdef25) {
		this.vdef25 = newVdef25;
	}

	/**
	 * 属性ntaxablesalemny的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDouble
	 */
	public UFDouble getNtaxablesalemny() {
		return ntaxablesalemny;
	}

	/**
	 * 属性ntaxablesalemny的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newNtaxablesalemny UFDouble
	 */
	public void setNtaxablesalemny(UFDouble newNtaxablesalemny) {
		this.ntaxablesalemny = newNtaxablesalemny;
	}

	/**
	 * 属性pk_basetype的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_basetype() {
		return pk_basetype;
	}

	/**
	 * 属性pk_basetype的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_basetype String
	 */
	public void setPk_basetype(String newPk_basetype) {
		this.pk_basetype = newPk_basetype;
	}

	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef19() {
		return vdef19;
	}

	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef19 String
	 */
	public void setVdef19(String newVdef19) {
		this.vdef19 = newVdef19;
	}

	/**
	 * 属性pk_deptdoc的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_deptdoc() {
		return pk_deptdoc;
	}

	/**
	 * 属性pk_deptdoc的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_deptdoc String
	 */
	public void setPk_deptdoc(String newPk_deptdoc) {
		this.pk_deptdoc = newPk_deptdoc;
	}

	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef3() {
		return vdef3;
	}

	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef3 String
	 */
	public void setVdef3(String newVdef3) {
		this.vdef3 = newVdef3;
	}

	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef13() {
		return vdef13;
	}

	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef13 String
	 */
	public void setVdef13(String newVdef13) {
		this.vdef13 = newVdef13;
	}

	/**
	 * 属性vreserve6的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVreserve6() {
		return vreserve6;
	}

	/**
	 * 属性vreserve6的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVreserve6 String
	 */
	public void setVreserve6(String newVreserve6) {
		this.vreserve6 = newVreserve6;
	}

	/**
	 * 属性pk_projanaly的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_projanaly() {
		return pk_projanaly;
	}

	/**
	 * 属性pk_projanaly的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_projanaly String
	 */
	public void setPk_projanaly(String newPk_projanaly) {
		this.pk_projanaly = newPk_projanaly;
	}

	/**
	 * 属性vreserve10的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVreserve10() {
		return vreserve10;
	}

	/**
	 * 属性vreserve10的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVreserve10 String
	 */
	public void setVreserve10(String newVreserve10) {
		this.vreserve10 = newVreserve10;
	}

	/**
	 * 属性vdef28的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef28() {
		return vdef28;
	}

	/**
	 * 属性vdef28的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef28 String
	 */
	public void setVdef28(String newVdef28) {
		this.vdef28 = newVdef28;
	}

	/**
	 * 属性ntaxableinmny的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDouble
	 */
	public UFDouble getNtaxableinmny() {
		return ntaxableinmny;
	}

	/**
	 * 属性ntaxableinmny的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newNtaxableinmny UFDouble
	 */
	public void setNtaxableinmny(UFDouble newNtaxableinmny) {
		this.ntaxableinmny = newNtaxableinmny;
	}

	/**
	 * 属性vreserve3的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVreserve3() {
		return vreserve3;
	}

	/**
	 * 属性vreserve3的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVreserve3 String
	 */
	public void setVreserve3(String newVreserve3) {
		this.vreserve3 = newVreserve3;
	}

	/**
	 * 属性vdef23的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef23() {
		return vdef23;
	}

	/**
	 * 属性vdef23的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef23 String
	 */
	public void setVdef23(String newVdef23) {
		this.vdef23 = newVdef23;
	}

	/**
	 * 属性vreserve4的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVreserve4() {
		return vreserve4;
	}

	/**
	 * 属性vreserve4的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVreserve4 String
	 */
	public void setVreserve4(String newVreserve4) {
		this.vreserve4 = newVreserve4;
	}

	/**
	 * 属性vdef29的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef29() {
		return vdef29;
	}

	/**
	 * 属性vdef29的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef29 String
	 */
	public void setVdef29(String newVdef29) {
		this.vdef29 = newVdef29;
	}

	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef10() {
		return vdef10;
	}

	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef10 String
	 */
	public void setVdef10(String newVdef10) {
		this.vdef10 = newVdef10;
	}

	/**
	 * 属性nlresttaxmny的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDouble
	 */
	public UFDouble getNlresttaxmny() {
		return nlresttaxmny;
	}

	/**
	 * 属性nlresttaxmny的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newNlresttaxmny UFDouble
	 */
	public void setNlresttaxmny(UFDouble newNlresttaxmny) {
		this.nlresttaxmny = newNlresttaxmny;
	}

	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef5() {
		return vdef5;
	}

	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef5 String
	 */
	public void setVdef5(String newVdef5) {
		this.vdef5 = newVdef5;
	}

	/**
	 * 属性pk_psndoc的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_psndoc() {
		return pk_psndoc;
	}

	/**
	 * 属性pk_psndoc的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_psndoc String
	 */
	public void setPk_psndoc(String newPk_psndoc) {
		this.pk_psndoc = newPk_psndoc;
	}

	/**
	 * 属性vreserve8的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVreserve8() {
		return vreserve8;
	}

	/**
	 * 属性vreserve8的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVreserve8 String
	 */
	public void setVreserve8(String newVreserve8) {
		this.vreserve8 = newVreserve8;
	}

	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef11() {
		return vdef11;
	}

	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef11 String
	 */
	public void setVdef11(String newVdef11) {
		this.vdef11 = newVdef11;
	}

	/**
	 * 属性nresttaxmny的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDouble
	 */
	public UFDouble getNresttaxmny() {
		return nresttaxmny;
	}

	/**
	 * 属性nresttaxmny的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newNresttaxmny UFDouble
	 */
	public void setNresttaxmny(UFDouble newNresttaxmny) {
		this.nresttaxmny = newNresttaxmny;
	}

	/**
	 * 属性dmakedate的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDate
	 */
	public UFDate getDmakedate() {
		return dmakedate;
	}

	/**
	 * 属性dmakedate的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newDmakedate UFDate
	 */
	public void setDmakedate(UFDate newDmakedate) {
		this.dmakedate = newDmakedate;
	}

	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef7() {
		return vdef7;
	}

	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef7 String
	 */
	public void setVdef7(String newVdef7) {
		this.vdef7 = newVdef7;
	}

	/**
	 * 属性nsaletaxmny的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDouble
	 */
	public UFDouble getNsaletaxmny() {
		return nsaletaxmny;
	}

	/**
	 * 属性nsaletaxmny的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newNsaletaxmny UFDouble
	 */
	public void setNsaletaxmny(UFDouble newNsaletaxmny) {
		this.nsaletaxmny = newNsaletaxmny;
	}

	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef20() {
		return vdef20;
	}

	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef20 String
	 */
	public void setVdef20(String newVdef20) {
		this.vdef20 = newVdef20;
	}

	/**
	 * 属性pk_billtype的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_billtype() {
		return pk_billtype;
	}

	/**
	 * 属性pk_billtype的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_billtype String
	 */
	public void setPk_billtype(String newPk_billtype) {
		this.pk_billtype = newPk_billtype;
	}

	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVbillstatus Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {
		this.vbillstatus = newVbillstatus;
	}

	/**
	 * 属性vreserve2的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVreserve2() {
		return vreserve2;
	}

	/**
	 * 属性vreserve2的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVreserve2 String
	 */
	public void setVreserve2(String newVreserve2) {
		this.vreserve2 = newVreserve2;
	}

	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef2() {
		return vdef2;
	}

	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef2 String
	 */
	public void setVdef2(String newVdef2) {
		this.vdef2 = newVdef2;
	}

	/**
	 * 属性vmemo的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVmemo() {
		return vmemo;
	}

	/**
	 * 属性vmemo的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVmemo String
	 */
	public void setVmemo(String newVmemo) {
		this.vmemo = newVmemo;
	}

	/**
	 * 属性nintaxmny的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDouble
	 */
	public UFDouble getNintaxmny() {
		return nintaxmny;
	}

	/**
	 * 属性nintaxmny的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newNintaxmny UFDouble
	 */
	public void setNintaxmny(UFDouble newNintaxmny) {
		this.nintaxmny = newNintaxmny;
	}

	/**
	 * 属性pk_busitype的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_busitype() {
		return pk_busitype;
	}

	/**
	 * 属性pk_busitype的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_busitype String
	 */
	public void setPk_busitype(String newPk_busitype) {
		this.pk_busitype = newPk_busitype;
	}

	/**
	 * 属性pk_projectbase的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_projectbase() {
		return pk_projectbase;
	}

	/**
	 * 属性pk_projectbase的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_projectbase String
	 */
	public void setPk_projectbase(String newPk_projectbase) {
		this.pk_projectbase = newPk_projectbase;
	}

	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef1() {
		return vdef1;
	}

	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef1 String
	 */
	public void setVdef1(String newVdef1) {
		this.vdef1 = newVdef1;
	}

	/**
	 * 属性vperiod的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVperiod() {
		return vperiod;
	}

	/**
	 * 属性vperiod的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVperiod String
	 */
	public void setVperiod(String newVperiod) {
		this.vperiod = newVperiod;
	}

	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVbillno() {
		return vbillno;
	}

	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVbillno String
	 */
	public void setVbillno(String newVbillno) {
		this.vbillno = newVbillno;
	}

	/**
	 * 属性dbilldate的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDate
	 */
	public UFDate getDbilldate() {
		return dbilldate;
	}

	/**
	 * 属性dbilldate的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newDbilldate UFDate
	 */
	public void setDbilldate(UFDate newDbilldate) {
		this.dbilldate = newDbilldate;
	}

	/**
	 * 属性vdef26的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef26() {
		return vdef26;
	}

	/**
	 * 属性vdef26的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef26 String
	 */
	public void setVdef26(String newVdef26) {
		this.vdef26 = newVdef26;
	}

	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef14() {
		return vdef14;
	}

	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef14 String
	 */
	public void setVdef14(String newVdef14) {
		this.vdef14 = newVdef14;
	}

	/**
	 * 属性vdef21的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef21() {
		return vdef21;
	}

	/**
	 * 属性vdef21的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef21 String
	 */
	public void setVdef21(String newVdef21) {
		this.vdef21 = newVdef21;
	}

	/**
	 * 属性pk_taxorg的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_taxorg() {
		return pk_taxorg;
	}

	/**
	 * 属性pk_taxorg的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_taxorg String
	 */
	public void setPk_taxorg(String newPk_taxorg) {
		this.pk_taxorg = newPk_taxorg;
	}

	/**
	 * 属性ntaxes的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDouble
	 */
	public UFDouble getNtaxes() {
		return ntaxes;
	}

	/**
	 * 属性ntaxes的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newNtaxes UFDouble
	 */
	public void setNtaxes(UFDouble newNtaxes) {
		this.ntaxes = newNtaxes;
	}

	/**
	 * 属性vreserve1的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVreserve1() {
		return vreserve1;
	}

	/**
	 * 属性vreserve1的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVreserve1 String
	 */
	public void setVreserve1(String newVreserve1) {
		this.vreserve1 = newVreserve1;
	}

	/**
	 * 属性vreserve7的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVreserve7() {
		return vreserve7;
	}

	/**
	 * 属性vreserve7的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVreserve7 String
	 */
	public void setVreserve7(String newVreserve7) {
		this.vreserve7 = newVreserve7;
	}

	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef9() {
		return vdef9;
	}

	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef9 String
	 */
	public void setVdef9(String newVdef9) {
		this.vdef9 = newVdef9;
	}

	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef8() {
		return vdef8;
	}

	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef8 String
	 */
	public void setVdef8(String newVdef8) {
		this.vdef8 = newVdef8;
	}

	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return UFDate
	 */
	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newDapprovedate UFDate
	 */
	public void setDapprovedate(UFDate newDapprovedate) {
		this.dapprovedate = newDapprovedate;
	}

	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVapproveid() {
		return vapproveid;
	}

	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVapproveid String
	 */
	public void setVapproveid(String newVapproveid) {
		this.vapproveid = newVapproveid;
	}

	/**
	 * 属性vdef30的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef30() {
		return vdef30;
	}

	/**
	 * 属性vdef30的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef30 String
	 */
	public void setVdef30(String newVdef30) {
		this.vdef30 = newVdef30;
	}

	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef6() {
		return vdef6;
	}

	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef6 String
	 */
	public void setVdef6(String newVdef6) {
		this.vdef6 = newVdef6;
	}

	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef15() {
		return vdef15;
	}

	public UFDouble getNthhadauthtaxmny() {
		return nthhadauthtaxmny;
	}

	public void setNthhadauthtaxmny(UFDouble nthhadauthtaxmny) {
		this.nthhadauthtaxmny = nthhadauthtaxmny;
	}

	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef15 String
	 */
	public void setVdef15(String newVdef15) {
		this.vdef15 = newVdef15;
	}

	/**
	 * 属性pk_receunit_base的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getPk_receunit_base() {
		return pk_receunit_base;
	}

	/**
	 * 属性pk_receunit_base的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newPk_receunit_base String
	 */
	public void setPk_receunit_base(String newPk_receunit_base) {
		this.pk_receunit_base = newPk_receunit_base;
	}

	/**
	 * 属性vdef22的Getter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @return String
	 */
	public String getVdef22() {
		return vdef22;
	}

	/**
	 * 属性vdef22的Setter方法.
	 * 创建日期:2016-04-10 14:23:45
	 * @param newVdef22 String
	 */
	public void setVdef22(String newVdef22) {
		this.vdef22 = newVdef22;
	}

	public UFDouble getNsalemny() {
		return nsalemny;
	}

	public void setNsalemny(UFDouble nsalemny) {
		this.nsalemny = nsalemny;
	}

	/**
	 * 本期费用扣除金额
	 * TODO
	 * sujbc2016-6-20上午7:34:09
	 */
	public UFDouble getNthcutmny() {
		return nthcutmny;
	}

	/**
	 * 本期费用扣除金额
	 * TODO
	 * sujbc2016-6-20上午7:34:19
	 */
	public void setNthcutmny(UFDouble nthdeductmny) {
		this.nthcutmny = nthdeductmny;
	}

	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2016-04-10 14:23:45
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2016-04-10 14:23:45
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
		return "pk_projanaly";
	}

	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2016-04-10 14:23:45
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "jzinv_vat_projanaly";
	}

	/**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2016-04-10 14:23:45
	  */
	public VatProjanalyVO() {
		super();
	}

	public String[] getBillCodeArray() {
		// TODO Auto-generated method stub
		return null;
	}
}
